dist: xenial
language: java

install:
- java --version

script:
- jshell --execution local ./build.jsh

after_success:
- BACH=${TRAVIS_BUILD_DIR}/src/bach/Bach.java

- cd "${TRAVIS_BUILD_DIR}/src/demo/000-main(a)"
- java ${BACH}

- cd "${TRAVIS_BUILD_DIR}/src/demo/010-main(a,b,c)"
- java ${BACH}

- cd "${TRAVIS_BUILD_DIR}/src/demo/100-main-a-test-a,t"
- java ${BACH}
